### ISSUE TITLE
Exporting Runnable JAR file from Eclipse

### ISSUE THREAD

**Issue by lucaghislo** [Team-di-Sviluppo-UniSIR/progetto_info3_progettazione_algoritmi_20_21#7]
Exported runnable JAR file won't execute.

![Screenshot 2021-01-17 213540](https://user-images.githubusercontent.com/36998696/104855655-3e071d80-590e-11eb-8bd9-98c36aa5a3bf.jpg)

**Comment by lucaghislo** [comment]
oh no!

**Comment by lucaparimbelli** [comment]
Seems like it's not working...

**Comment by lucaghislo** [comment]
it looks like so
